# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "instagram"
name = "Instagram"
url = "https://www.instagram.com/horvaticus"

[social.params]
icon = "brand-instagram"

[[social]]
identifier = "tiktok"
name = "TikTok"
url = "https://www.tiktok.com/@horvaticus"

[social.params]
icon = "brand-tiktok"

[[social]]
identifier = "bluesky"
name = "BlueSky"
url = "https://bsky.app/profile/zack.zip"

[social.params]
icon = "brand-bluesky"

[[social]]
identifier = "twitter"
name = "The website formerly known as Twitter"
url = "https://x.com/horvaticus"

[social.params]
icon = "brand-twitter"

[[social]]
identifier = "twitch"
name = "Twitch"
url = "https://www.twitch.tv/horvaticus"

[social.params]
icon = "brand-twitch"

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/zackhorvath"

[social.params]
icon = "brand-github"